version: "3.9"

services:
  api_server:
    image: cosmtrek/air:latest
    container_name: api_server
    restart: always
    tty: true
    stdin_open: true
    working_dir: /workspaces
    environment:
      - TZ=Asia/Tokyo
      - DB_USER=app
      - DB_PASSWORD=password
      - DB_PORT=5432
      - DB_HOST=db
      - DB_DATABASE=app
      - SERVER_PORT=8080
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/workspaces

  db:
    image: postgres:15.4
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    volumes:
      - ./docker/data:/tmp/data
      - ./docker/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app}"]
      interval: 5s
      retries: 3
    # image: mysql:8.0
    # container_name: mysql_db
    # restart: always
    # ports:
    #   - "3306:3306"
    # environment:
    #   - TZ=Asia/Tokyo
    #   - MYSQL_ROOT_PASSWORD=password
    #   - MYSQL_DATABASE=app
    #   - MYSQL_USER=app
    #   - MYSQL_PASSWORD=password
    # volumes:
    #   - ./docker/data:/var/lib/mysql
    #   - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5