# Gooseコマンド
migrate-up:
	docker compose run --rm migration up --dir /migrations

migrate-down:
	docker compose run --rm migration down --dir /migrations

migrate-status:
	docker compose run --rm migration status --dir /migrations
